
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Api.Models.Requests
{
    using Api.Models.Components;
    using Api.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// The input document
    /// </summary>
    public class ExecutePolicyWithInputRequestBody
    {

        /// <summary>
        /// Arbitrary JSON used within your policies by accessing `input`
        /// </summary>
        [JsonProperty("input")]
        public Input Input { get; set; } = default!;
    }
}