//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Styra.Opa.OpenApi.Models.Requests
{
    using Newtonsoft.Json;
    using Styra.Opa.OpenApi.Models.Components;
    using Styra.Opa.OpenApi.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// The query, input, and other settings for partial evaluation.
    /// </summary>
    public class CompileQueryWithPartialEvaluationRequestBody
    {

        /// <summary>
        /// The query to partially evaluate and compile.
        /// </summary>
        [JsonProperty("query")]
        public string Query { get; set; } = default!;

        /// <summary>
        /// Additional options to use during partial evaluation. Only the disableInlining option is currently supported in OPA. Enterprise OPA may support additional options.
        /// </summary>
        [JsonProperty("options")]
        public CompileOptions? Options { get; set; }

        /// <summary>
        /// The terms to treat as unknown during partial evaluation.
        /// </summary>
        [JsonProperty("unknowns")]
        public List<string>? Unknowns { get; set; }

        /// <summary>
        /// Arbitrary JSON used within your policies by accessing `input`
        /// </summary>
        [JsonProperty("input")]
        public Input? Input { get; set; }
    }
}