//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Styra.Opa.OpenApi.Models.Requests
{
    using Styra.Opa.OpenApi.Models.Components;
    using Styra.Opa.OpenApi.Models.Requests;
    using Styra.Opa.OpenApi.Utils;
    
    public class CompileQueryWithPartialEvaluationRequest
    {

        /// <summary>
        /// Indicates the server should respond with a gzip encoded body. The server will send the compressed response only if its length is above `server.encoding.gzip.min_length` value. See the configuration section
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=Accept-Encoding")]
        public GzipAcceptEncoding? AcceptEncoding { get; set; }

        /// <summary>
        /// Indicates that the request body is gzip encoded
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=Content-Encoding")]
        public GzipContentEncoding? ContentEncoding { get; set; }

        /// <summary>
        /// If parameter is `true`, response will formatted for humans.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=pretty")]
        public bool? Pretty { get; set; }

        /// <summary>
        /// Return query explanation in addition to result.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=explain")]
        public Explain? Explain { get; set; }

        /// <summary>
        /// Return query performance metrics in addition to result.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=metrics")]
        public bool? Metrics { get; set; }

        /// <summary>
        /// Instrument query evaluation and return a superset of performance metrics in addition to result.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=instrument")]
        public bool? Instrument { get; set; }

        /// <summary>
        /// The query, input, and other settings for partial evaluation.
        /// </summary>
        [SpeakeasyMetadata("request:mediaType=application/json")]
        public CompileQueryWithPartialEvaluationRequestBody RequestBody { get; set; } = default!;
    }
}