//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Styra.Opa.OpenApi.Models.Requests
{
    using Styra.Opa.OpenApi.Models.Components;
    using Styra.Opa.OpenApi.Utils;
    using System.Collections.Generic;
    using System.Net.Http;
    using System;
    
    public class ExecuteBatchPolicyWithInputResponse
    {

        /// <summary>
        /// HTTP response content type for this operation
        /// </summary>
        public string? ContentType { get; set; } = default!;

        /// <summary>
        /// HTTP response status code for this operation
        /// </summary>
        public int StatusCode { get; set; } = default!;

        /// <summary>
        /// Raw HTTP response; suitable for custom response parsing
        /// </summary>
        public HttpResponseMessage RawResponse { get; set; } = default!;

        /// <summary>
        /// All batched policy executions succeeded.<br/>
        /// 
        /// <remarks>
        /// The server also returns 200 if the path refers to an undefined document. In this case, responses will be empty.<br/>
        /// 
        /// </remarks>
        /// </summary>
        public BatchSuccessfulPolicyEvaluation? BatchSuccessfulPolicyEvaluation { get; set; }

        /// <summary>
        /// Mixed success and failures.
        /// </summary>
        public BatchMixedResults? BatchMixedResults { get; set; }

        public Dictionary<string, List<string>> Headers { get; set; } = default!;
    }
}