
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Styra.OpenApi.Models.Components
{
    using Newtonsoft.Json;
    using Styra.OpenApi.Models.Components;
    using Styra.OpenApi.Utils;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Provenance information can be requested on individual API calls and are returned inline with the API response. To obtain provenance information on an API call, specify the `provenance=true` query parameter when executing the API call.
    /// </summary>
    public class Provenance
    {

        [JsonProperty("version")]
        public string? Version { get; set; }

        [JsonProperty("build_commit")]
        public string? BuildCommit { get; set; }

        [JsonProperty("build_timestamp")]
        public DateTime? BuildTimestamp { get; set; }

        [JsonProperty("build_host")]
        public string? BuildHost { get; set; }

        [JsonProperty("bundles")]
        public Dictionary<string, Revision>? Bundles { get; set; }
    }
}