
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Api.SDK.Models.Components
{
    using Newtonsoft.Json;
    
    public class Revision
    {

        [JsonProperty("revision")]
        public string RevisionValue { get; set; } = default!;
    }
}