name: 3b – Publish Docs

# Trigger the action on push to main
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  actions: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-docs:
    env:
      STYRA_GH_PAGES_URL: https://styrainc.github.io/opa-csharp
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Patch Speakeasy README docs links
        run: ./scripts/patch-readme.sh README.md ${{ env.STYRA_GH_PAGES_URL }}

      - name: Dotnet Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - run: dotnet tool update -g docfx
      - run: docfx docs/docfx.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "docs/_site"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
