name: "Manually Publish Package to NuGet"

# This workflow is intended for populating the initial NuGet package.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget

jobs:
  manual-build-and-publish:
    name: Manually Build and Publish NuGet Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # Get all history for automatic versioning
          persist-credentials: false

      - name: Setup dotnet
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Get current version
        id: current_version
        run: |
          $currentVersion = (Select-Xml -Path src/OpenPolicyAgent.Opa/OpenPolicyAgent.Opa.csproj -XPath "//PackageVersion").Node.InnerText
          echo "CURRENT_VERSION=$currentVersion" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Pack
        run: dotnet pack --configuration Release --output "$NuGetDirectory" --no-build

      - name: Publish NuGet package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          foreach($file in (Get-ChildItem "$env:NuGetDirectory" -Filter *.nupkg)) {
            dotnet nuget push $file --api-key "$env:NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }
        shell: pwsh
