//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Styra.Opa.OpenApi.Models.Components
{
    using Newtonsoft.Json;
    using Styra.Opa.OpenApi.Models.Components;
    using Styra.Opa.OpenApi.Utils;
    using System.Collections.Generic;
    
    public class BatchSuccessfulPolicyEvaluation
    {

        [JsonProperty("batch_decision_id")]
        public string? BatchDecisionId { get; set; }

        /// <summary>
        /// If query metrics are enabled, this field contains query performance metrics collected during the parse, compile, and evaluation steps.
        /// </summary>
        [JsonProperty("metrics")]
        public Dictionary<string, object>? Metrics { get; set; }

        [JsonProperty("responses")]
        public Dictionary<string, SuccessfulPolicyResponse>? Responses { get; set; }
    }
}