//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Styra.Opa.OpenApi.Models.Components
{
    using Newtonsoft.Json;
    using Styra.Opa.OpenApi.Models.Components;
    using Styra.Opa.OpenApi.Utils;
    
    /// <summary>
    /// The partially evaluated result of the query. Result will be empty if the query is never true.
    /// </summary>
    public class CompileResultJSON
    {

        /// <summary>
        /// The partially evaluated result of the query.
        /// </summary>
        [JsonProperty("result")]
        public CompileResultJSONResult? Result { get; set; }
    }
}