//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Styra.Opa.OpenApi.Models.Components
{
    using Newtonsoft.Json;
    using Styra.Opa.OpenApi.Models.Components;
    using Styra.Opa.OpenApi.Utils;
    using System.Collections.Generic;
    
    public class CompileResultMultitargetPostgresql
    {

        /// <summary>
        /// String representing the SQL equivalent of the conditions under which the query is true
        /// </summary>
        [JsonProperty("query")]
        public string? Query { get; set; }

        /// <summary>
        /// Column masking functions, where the key is the column name, and the value describes which masking function to use.
        /// </summary>
        [JsonProperty("masks")]
        public Dictionary<string, MaskingRule>? Masks { get; set; }
    }
}