//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Styra.Opa.OpenApi.Models.Components
{
    using Newtonsoft.Json;
    using Styra.Opa.OpenApi.Utils;
    using System;
    
    public enum GzipContentEncoding
    {
        [JsonProperty("gzip")]
        Gzip,
    }

    public static class GzipContentEncodingExtension
    {
        public static string Value(this GzipContentEncoding value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GzipContentEncoding ToEnum(this string value)
        {
            foreach(var field in typeof(GzipContentEncoding).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GzipContentEncoding)
                    {
                        return (GzipContentEncoding)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GzipContentEncoding");
        }
    }

}