//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Styra.Opa.OpenApi.Models.Components
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using Styra.Opa.OpenApi.Utils;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    using System;
    

    public class InputType
    {
        private InputType(string value) { Value = value; }

        public string Value { get; private set; }
        public static InputType Boolean { get { return new InputType("boolean"); } }
        
        public static InputType Str { get { return new InputType("str"); } }
        
        public static InputType Number { get { return new InputType("number"); } }
        
        public static InputType ArrayOfAny { get { return new InputType("arrayOfAny"); } }
        
        public static InputType MapOfAny { get { return new InputType("mapOfAny"); } }
        
        public static InputType Null { get { return new InputType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(InputType v) { return v.Value; }
        public static InputType FromString(string v) {
            switch(v) {
                case "boolean": return Boolean;
                case "str": return Str;
                case "number": return Number;
                case "arrayOfAny": return ArrayOfAny;
                case "mapOfAny": return MapOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for InputType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((InputType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Arbitrary JSON used within your policies by accessing `input`
    /// </summary>
    [JsonConverter(typeof(Input.InputConverter))]
    public class Input {
        public Input(InputType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public Dictionary<string, object>? MapOfAny { get; set; }

        public InputType Type { get; set; }


        public static Input CreateBoolean(bool boolean) {
            InputType typ = InputType.Boolean;

            Input res = new Input(typ);
            res.Boolean = boolean;
            return res;
        }

        public static Input CreateStr(string str) {
            InputType typ = InputType.Str;

            Input res = new Input(typ);
            res.Str = str;
            return res;
        }

        public static Input CreateNumber(double number) {
            InputType typ = InputType.Number;

            Input res = new Input(typ);
            res.Number = number;
            return res;
        }

        public static Input CreateArrayOfAny(List<object> arrayOfAny) {
            InputType typ = InputType.ArrayOfAny;

            Input res = new Input(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static Input CreateMapOfAny(Dictionary<string, object> mapOfAny) {
            InputType typ = InputType.MapOfAny;

            Input res = new Input(typ);
            res.MapOfAny = mapOfAny;
            return res;
        }

        public static Input CreateNull() {
            InputType typ = InputType.Null;
            return new Input(typ);
        }

        public class InputConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(Input);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new Input(InputType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new Input(InputType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new Input(InputType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new Input(InputType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new Input(InputType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Input(InputType.MapOfAny)
                    {
                        MapOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Dictionary<string, object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Dictionary<string, object>), new Input(InputType.MapOfAny), "MapOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                Input res = (Input)value;
                if (InputType.FromString(res.Type).Equals(InputType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }
                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }
                if (res.MapOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MapOfAny));
                    return;
                }

            }

        }

    }
}