//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Styra.Opa.OpenApi.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Styra.Opa.OpenApi.Models.Components;
    using Styra.Opa.OpenApi.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class MaskingRuleType
    {
        private MaskingRuleType(string value) { Value = value; }

        public string Value { get; private set; }
        public static MaskingRuleType One { get { return new MaskingRuleType("1"); } }
        
        public static MaskingRuleType Null { get { return new MaskingRuleType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(MaskingRuleType v) { return v.Value; }
        public static MaskingRuleType FromString(string v) {
            switch(v) {
                case "1": return One;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for MaskingRuleType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((MaskingRuleType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(MaskingRule.MaskingRuleConverter))]
    public class MaskingRule {
        public MaskingRule(MaskingRuleType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public One? One { get; set; }

        public MaskingRuleType Type { get; set; }


        public static MaskingRule CreateOne(One one) {
            MaskingRuleType typ = MaskingRuleType.One;

            MaskingRule res = new MaskingRule(typ);
            res.One = one;
            return res;
        }

        public static MaskingRule CreateNull() {
            MaskingRuleType typ = MaskingRuleType.Null;
            return new MaskingRule(typ);
        }

        public class MaskingRuleConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(MaskingRule);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new MaskingRule(MaskingRuleType.One)
                    {
                        One = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<One>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(One), new MaskingRule(MaskingRuleType.One), "One"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                MaskingRule res = (MaskingRule)value;
                if (MaskingRuleType.FromString(res.Type).Equals(MaskingRuleType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.One != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.One));
                    return;
                }

            }

        }

    }
}