//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Styra.Opa.OpenApi.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Styra.Opa.OpenApi.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class ReplaceType
    {
        private ReplaceType(string value) { Value = value; }

        public string Value { get; private set; }
        public static ReplaceType Boolean { get { return new ReplaceType("boolean"); } }
        
        public static ReplaceType Str { get { return new ReplaceType("str"); } }
        
        public static ReplaceType Number { get { return new ReplaceType("number"); } }
        
        public static ReplaceType ArrayOfAny { get { return new ReplaceType("arrayOfAny"); } }
        
        public static ReplaceType MapOfAny { get { return new ReplaceType("mapOfAny"); } }
        
        public static ReplaceType Null { get { return new ReplaceType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(ReplaceType v) { return v.Value; }
        public static ReplaceType FromString(string v) {
            switch(v) {
                case "boolean": return Boolean;
                case "str": return Str;
                case "number": return Number;
                case "arrayOfAny": return ArrayOfAny;
                case "mapOfAny": return MapOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for ReplaceType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ReplaceType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(Replace.ReplaceConverter))]
    public class Replace {
        public Replace(ReplaceType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public Dictionary<string, object>? MapOfAny { get; set; }

        public ReplaceType Type { get; set; }


        public static Replace CreateBoolean(bool boolean) {
            ReplaceType typ = ReplaceType.Boolean;

            Replace res = new Replace(typ);
            res.Boolean = boolean;
            return res;
        }

        public static Replace CreateStr(string str) {
            ReplaceType typ = ReplaceType.Str;

            Replace res = new Replace(typ);
            res.Str = str;
            return res;
        }

        public static Replace CreateNumber(double number) {
            ReplaceType typ = ReplaceType.Number;

            Replace res = new Replace(typ);
            res.Number = number;
            return res;
        }

        public static Replace CreateArrayOfAny(List<object> arrayOfAny) {
            ReplaceType typ = ReplaceType.ArrayOfAny;

            Replace res = new Replace(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static Replace CreateMapOfAny(Dictionary<string, object> mapOfAny) {
            ReplaceType typ = ReplaceType.MapOfAny;

            Replace res = new Replace(typ);
            res.MapOfAny = mapOfAny;
            return res;
        }

        public static Replace CreateNull() {
            ReplaceType typ = ReplaceType.Null;
            return new Replace(typ);
        }

        public class ReplaceConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(Replace);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new Replace(ReplaceType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new Replace(ReplaceType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new Replace(ReplaceType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new Replace(ReplaceType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new Replace(ReplaceType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Replace(ReplaceType.MapOfAny)
                    {
                        MapOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Dictionary<string, object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Dictionary<string, object>), new Replace(ReplaceType.MapOfAny), "MapOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                Replace res = (Replace)value;
                if (ReplaceType.FromString(res.Type).Equals(ReplaceType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }
                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }
                if (res.MapOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MapOfAny));
                    return;
                }

            }

        }

    }
}