//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Styra.Opa.OpenApi.Models.Components
{
    using Newtonsoft.Json;
    using Styra.Opa.OpenApi.Models.Components;
    using Styra.Opa.OpenApi.Utils;
    
    public class Targets
    {

        [JsonProperty("ucast")]
        public Ucast? Ucast { get; set; }

        [JsonProperty("sqlserver")]
        public Sqlserver? Sqlserver { get; set; }

        [JsonProperty("mysql")]
        public Mysql? Mysql { get; set; }

        [JsonProperty("postgresql")]
        public Postgresql? Postgresql { get; set; }

        [JsonProperty("sqlite")]
        public Sqlite? Sqlite { get; set; }
    }
}